on: [push]

jobs:
  jenkins-lts:
    runs-on: ubuntu-latest
    name: test on jenkins-lts
    steps:
      - name: test jenkins-lts
        id: jenkins-lts
        uses: gdemengin/pipeline-logparser@test
