on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron:  '0 19 * * 2'


jobs:
  jenkins-lts:
    runs-on: ubuntu-latest
    name: test on jenkins-lts
    steps:
      - uses: actions/checkout@v3
      - name: test jenkins-lts
        uses: ./.github/jenkins-lts/
  jenkins-last:
    runs-on: ubuntu-latest
    name: test on jenkins last good version
    steps:
      - uses: actions/checkout@v3
      - name: test jenkins-last
        uses: ./.github/jenkins-last/
